version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - kuksa-databroker
  kuksa-databroker:
    image: kuksa-databroker
    container_name: kuksa-databroker-instance
    network_mode: host
    stdin_open: true
    tty: true
    restart: no
    deploy:
      resources:
        limits:
          cpus: '1.0'    # 0.5 CPU cores maximum
          memory: '1G'  # 256MB of memory maximum
        reservations:
          cpus: '1.0'    # 0.5 CPU cores minimum
          memory: '1G'  # 256MB of memory minimum
  # node-exporter:
  #   image: prom/node-exporter:v1.4.0
  #   container_name: node-exporter
  #   network_mode: host
  #   ports:
  #     - "9100:9100"
  #   restart: unless-stopped


  grafana:
    image: grafana/grafana:9.2.0
    network_mode: "host" 
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  grafana-data:
